apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: final-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/OMAR-BESHIR/k8s-manifests.git'
    targetRevision: main
    path: .

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ivolve

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

